import type { Genre, MobilePerformanceBudget, MonetizationModel, ScaffoldFile } from '@egf/core';
import {
  ANALYTICS_GD,
  AUDIO_MANAGER_GD,
  GAME_STATE_GD,
  GAMEPLAY_IDLE_GD,
  GAMEPLAY_PUZZLE_GD,
  GAMEPLAY_RUNNER_GD,
  MAIN_GD,
  MONETIZATION_GD,
  gameplayTscn,
  mainTscn,
} from './gdTemplates';

export interface MobileScaffoldInput {
  projectName: string;
  slug: string;
  genre: Genre;
  packageId: string;
  orientation: 'portrait' | 'landscape' | 'sensor';
  targetFps: number;
  monetization: MonetizationModel[];
}

export function defaultPackageId(slug: string): string {
  const cleaned = slug
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '')
    .replace(/^[0-9]+/, '');
  return `com.empireforge.${cleaned || 'game'}`;
}

export function defaultPerformanceBudget(genre: Genre): MobilePerformanceBudget {
  switch (genre) {
    case 'hypercasual':
    case 'runner':
    case 'merge':
    case 'puzzle':
      return { targetFps: 60, maxMemoryMb: 300, maxApkSizeMb: 60, maxColdStartSeconds: 3, maxDrawCalls: 120 };
    case 'idle':
    case 'tycoon':
    case 'simulator':
    case 'hybridcasual':
    case 'card_battler':
      return { targetFps: 60, maxMemoryMb: 400, maxApkSizeMb: 100, maxColdStartSeconds: 4, maxDrawCalls: 200 };
    case 'rpg_lite':
    case 'survival':
    case 'roguelite':
    case 'tower_defense':
    case 'battle_arena':
    case 'racing':
    case 'sports':
    case 'sandbox':
      return { targetFps: 30, maxMemoryMb: 500, maxApkSizeMb: 150, maxColdStartSeconds: 5, maxDrawCalls: 300 };
    default:
      return { targetFps: 60, maxMemoryMb: 400, maxApkSizeMb: 100, maxColdStartSeconds: 4, maxDrawCalls: 200 };
  }
}

type GameplayTemplate = { scriptFile: string; script: string };

function gameplayFor(genre: Genre): GameplayTemplate {
  const runnerLike: Genre[] = ['runner', 'hypercasual', 'racing', 'obby', 'sports'];
  const idleLike: Genre[] = ['idle', 'tycoon', 'simulator', 'merge', 'hybridcasual', 'sandbox'];
  if (runnerLike.includes(genre)) return { scriptFile: 'gameplay_runner.gd', script: GAMEPLAY_RUNNER_GD };
  if (idleLike.includes(genre)) return { scriptFile: 'gameplay_idle.gd', script: GAMEPLAY_IDLE_GD };
  return { scriptFile: 'gameplay_puzzle.gd', script: GAMEPLAY_PUZZLE_GD };
}

function orientationSetting(orientation: MobileScaffoldInput['orientation']): number {
  // Godot DisplayServer.ScreenOrientation: 0 landscape, 1 portrait, 6 sensor.
  return orientation === 'landscape' ? 0 : orientation === 'portrait' ? 1 : 6;
}

function buildProjectGodot(input: MobileScaffoldInput, withMonetization: boolean): string {
  const autoloads = [
    'GameState="*res://scripts/autoload/game_state.gd"',
    'AudioManager="*res://scripts/autoload/audio_manager.gd"',
    'Analytics="*res://scripts/autoload/analytics.gd"',
    ...(withMonetization ? ['Monetization="*res://scripts/autoload/monetization.gd"'] : []),
  ].join('\n');

  return `; Engine configuration - generated by Empire Game Forge AI (Godot 4.3)
config_version=5

[application]

config/name="${input.projectName}"
config/version="0.1.0"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.3", "Mobile")

[autoload]

${autoloads}

[display]

window/size/viewport_width=720
window/size/viewport_height=1280
window/handheld/orientation=${orientationSetting(input.orientation)}
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[rendering]

renderer/rendering_method="mobile"
renderer/rendering_method.mobile="mobile"

[input_devices]

pointing/emulate_touch_from_mouse=true
`;
}

function buildExportPresetsExample(input: MobileScaffoldInput, budget: MobilePerformanceBudget): string {
  return `; Vorlage für export_presets.cfg (in Godot: Projekt -> Export -> Android).
; SICHERHEIT: Keystore-Pfade/Passwörter NIEMALS einchecken - Godot trägt sie
; lokal ein. Diese Datei ist nur eine Referenz (.example).

[preset.0]

name="Android"
platform="Android"
runnable=true
export_filter="all_resources"
export_path="build/${input.slug}.aab"

[preset.0.options]

package/unique_name="${input.packageId}"
package/name="${input.projectName}"
version/code=1
version/name="0.1.0"
architectures/arm64-v8a=true
architectures/armeabi-v7a=false
gradle_build/use_gradle_build=true
gradle_build/min_sdk="24"
gradle_build/target_sdk="34"
; Ziel-APK/AAB-Größe laut Performance-Budget: max. ${budget.maxApkSizeMb} MB
`;
}

function buildExportDoc(input: MobileScaffoldInput): string {
  return `# Android-Export — Schritt für Schritt

1. **Godot 4.3+** von godotengine.org laden (keine Installation nötig).
2. Projekt öffnen: Godot-Projektmanager → Importieren → \`project.godot\` in diesem Ordner.
3. **Android Build Template**: Editor → Projekt → "Android-Build-Vorlage installieren".
4. **Export-Vorlagen**: Editor → Editor-Einstellungen → Export → Android: Pfade zu Android SDK + JDK setzen (Android Studio liefert beides).
5. **Debug-Export**: Projekt → Export → Android → "Projekt exportieren" → APK aufs Gerät (USB-Debugging) und testen.
6. **Release-Signing**: Keystore erzeugen (\`keytool -genkey ...\`), in Godot unter Export → Android → Keystore eintragen. **Keystore + Passwörter niemals ins Repo!**
7. **Play Store**: AAB exportieren (\`gradle_build/use_gradle_build=true\`), in der Play Console als Internal Testing Track hochladen, Pre-Launch-Report prüfen.
8. Paket-ID ist **${input.packageId}** — nach dem ersten Upload nicht mehr änderbar.

Checklisten (App-Store + Datenschutz) in Empire Game Forge unter „Checklisten" abarbeiten, bevor irgendetwas veröffentlicht wird.
`;
}

function buildPerformanceDoc(budget: MobilePerformanceBudget, genre: Genre): string {
  return `# Performance-Budget (${genre})

| Metrik | Budget |
| --- | --- |
| Ziel-FPS | ${budget.targetFps} |
| Speicher (RAM) | max. ${budget.maxMemoryMb} MB |
| APK/AAB-Größe | max. ${budget.maxApkSizeMb} MB |
| Kaltstart | max. ${budget.maxColdStartSeconds} s |
| Draw Calls | max. ${budget.maxDrawCalls} |

Regeln, die dieses Template bereits umsetzt:
- Objekt-Pooling statt ständigem Instanziieren (siehe Runner-Spawner).
- Mobile-Renderer, ein CanvasLayer, programmatische UI ohne große Texturen.
- Autosave nur bei Pause/Beenden statt jedem Frame.

Beim Erweitern: Godot-Profiler (Debugger → Profiler) auf dem ECHTEN Zielgerät
laufen lassen, Texturen als komprimierte Formate importieren, Partikel deckeln.
`;
}

export function buildGodotScaffold(input: MobileScaffoldInput): ScaffoldFile[] {
  const withMonetization = input.monetization.some((m) =>
    ['rewarded_ads', 'interstitial_ads', 'iap_consumables', 'iap_non_consumables', 'battle_pass', 'cosmetics', 'subscription'].includes(m),
  );
  const gameplay = gameplayFor(input.genre);
  const budget = defaultPerformanceBudget(input.genre);

  const files: ScaffoldFile[] = [
    { path: 'project.godot', content: buildProjectGodot(input, withMonetization) },
    { path: 'scenes/main.tscn', content: mainTscn() },
    { path: 'scenes/gameplay.tscn', content: gameplayTscn(gameplay.scriptFile) },
    { path: 'scripts/main.gd', content: MAIN_GD },
    { path: `scripts/${gameplay.scriptFile}`, content: gameplay.script },
    { path: 'scripts/autoload/game_state.gd', content: GAME_STATE_GD },
    { path: 'scripts/autoload/audio_manager.gd', content: AUDIO_MANAGER_GD },
    { path: 'scripts/autoload/analytics.gd', content: ANALYTICS_GD },
    { path: 'export_presets.cfg.example', content: buildExportPresetsExample(input, budget) },
    { path: 'docs/EXPORT_ANDROID.md', content: buildExportDoc(input) },
    { path: 'docs/PERFORMANCE.md', content: buildPerformanceDoc(budget, input.genre) },
    {
      path: 'README.md',
      content: `# ${input.projectName} — Godot-Projekt

Generiert von Empire Game Forge AI (Godot 4.3, GDScript, Touch-first).

- Öffnen: Godot-Projektmanager → Importieren → \`project.godot\`
- Starten: F5 (Hauptszene \`scenes/main.tscn\`)
- Gameplay-Template: \`scripts/${gameplay.scriptFile}\` (Genre: ${input.genre})
- Save-System: \`scripts/autoload/game_state.gd\` (JSON in \`user://save.json\`)
- Android-Export: \`docs/EXPORT_ANDROID.md\` · Performance: \`docs/PERFORMANCE.md\`
`,
    },
    { path: '.gitignore', content: 'build/\n.godot/\nexport_presets.cfg\n*.keystore\n' },
  ];
  if (withMonetization) {
    files.push({ path: 'scripts/autoload/monetization.gd', content: MONETIZATION_GD });
  }
  return files;
}
